[features]
seeds = false
skip-lint = false
[programs.localnet]
re_dao = "FmdvrZeUEDTgrDfGC1113PmevZo9tnAW89AWaRWsCDHk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ldev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
